version: "3"

services:
  # API backend
  api:
    container_name: api-kube-starter
    env_file: .env
    build:
      context: ./api
      dockerfile: Dockerfile.dev

    environment:
      - ENV=$ENV
      - PORT=$PORT
      - HOST=$HOST
      - MONGODB_DB_NAME=$MONGODB_DB_NAME
      - MONGODB_USER=$MONGODB_USER
      - MONGODB_PASSWORD=$MONGODB_PASSWORD
      - MONGODB_HOST=$MONGODB_HOST
      - MONGODB_PORT=$MONGODB_PORT
      - DATABASE_URL=$DATABASE_URL
      - MONGO_INITDB_DATABASE=$MONGO_INITDB_DATABASE
      - ACCESS_TOKEN_EXPIRE_MINUTES=$ACCESS_TOKEN_EXPIRE_MINUTES
      - JWT_ALGORITHM=$JWT_ALGORITHM
      - CLIENT_ORIGIN=$CLIENT_ORIGIN
      - SECRET_KEY=$SECRET_KEY

    volumes:
      - ./api:/app

    ports:
      - 8000:8000
    depends_on:
      - mongo

  # Mongo DB
  mongo:
    image: mongo:latest
    container_name: mongodb-kube-starter
    env_file: .env

    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_INITDB_ROOT_PASSWORD
      - MONGO_INITDB_DATABASE=$MONGO_INITDB_DATABASE

    volumes:
      - ./data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    ports:
      - 8003:27017
