apiVersion: v1
items:
  # --- API BACKEND ---

  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      labels:
        app: kube-starter-api
      name: kube-starter-api
      namespace: kube-starter
    spec:
      progressDeadlineSeconds: 600
      replicas: 1
      revisionHistoryLimit: 10
      selector:
        matchLabels:
          app: kube-starter-api
      strategy:
        rollingUpdate:
          maxSurge: 25%
          maxUnavailable: 25%
        type: RollingUpdate
      template:
        metadata:
          labels:
            app: kube-starter-api
        spec:
          containers:
            - image: docker-user/kube-starter-api:0.10
              imagePullPolicy: IfNotPresent
              name: kube-starter-api
              envFrom:
                - configMapRef:
                    name: kube-starter-config

          imagePullSecrets:
            - name: regcred-docker

  # --- WWW BACKEND ---

  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      labels:
        app: kube-starter-www
      name: kube-starter-www
      namespace: kube-starter
    spec:
      progressDeadlineSeconds: 600
      replicas: 1
      revisionHistoryLimit: 10
      selector:
        matchLabels:
          app: kube-starter-www
      strategy:
        rollingUpdate:
          maxSurge: 25%
          maxUnavailable: 25%
        type: RollingUpdate
      template:
        metadata:
          labels:
            app: kube-starter-www
        spec:
          containers:
            - image: docker-user/kube-starter-www:0.10
              imagePullPolicy: IfNotPresent
              name: kube-starter-www
              envFrom:
                - configMapRef:
                    name: kube-starter-config

          imagePullSecrets:
            - name: regcred-docker

kind: List
metadata:
  resourceVersion: ""
