apiVersion: v1
items:
  # --- API BACKEND ---
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      labels:
        app: fastpyfolio-api
      name: fastpyfolio-api
      namespace: fastpyfolio
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: fastpyfolio-api
      template:
        metadata:
          labels:
            app: fastpyfolio-api
        spec:
          containers:
            - image: subaquaticpierre/fastpyfolio-api:0.42
              imagePullPolicy: IfNotPresent
              name: fastpyfolio-api
              envFrom:
                - configMapRef:
                    name: fastpyfolio-api-config

              volumeMounts:
                - name: api-uploads
                  mountPath: /app/uploads

          volumes:
            - name: api-uploads
              persistentVolumeClaim:
                claimName: api-uploads-pvc

          # imagePullSecrets:
          #   - name: regcred-docker

  # --- WWW BACKEND ---
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      labels:
        app: fastpyfolio-www
      name: fastpyfolio-www
      namespace: fastpyfolio
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: fastpyfolio-www
      template:
        metadata:
          labels:
            app: fastpyfolio-www
        spec:
          containers:
            - image: subaquaticpierre/fastpyfolio-www:0.42
              imagePullPolicy: IfNotPresent
              name: fastpyfolio-www
              envFrom:
                - configMapRef:
                    name: fastpyfolio-www-config

          # imagePullSecrets:
          #   - name: regcred-docker

kind: List
metadata:
  resourceVersion: ""
