apiVersion: v1
items:
  # --- DEPLOYMENT ---

  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      labels:
        app: kube-starter-mongodb
      name: kube-starter-mongodb
      namespace: kube-starter
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: kube-starter-mongodb
      template:
        metadata:
          labels:
            app: kube-starter-mongodb
            selector: kube-starter-mongodb
        spec:
          containers:
            - name: kube-starter-mongodb
              image: mongo:6.0
              env:
                - name: MONGO_INITDB_ROOT_USERNAME_FILE
                  value: /etc/k8-test/admin/MONGO_ROOT_USERNAME
                - name: MONGO_INITDB_ROOT_PASSWORD_FILE
                  value: /etc/k8-test/admin/MONGO_ROOT_PASSWORD
              volumeMounts:
                - name: k8-test
                  mountPath: /etc/k8-test
                  readOnly: true
                - name: mongodb-scripts
                  mountPath: /docker-entrypoint-initdb.d
                  readOnly: true
                - name: mongodb-configmap
                  mountPath: /config
                  readOnly: true
                - name: mongodb-data
                  mountPath: /data/db

          nodeSelector:
            name: thor-vm-demo1

          volumes:
            - name: k8-test
              secret:
                secretName: mongodb-secret
                items:
                  - key: MONGO_ROOT_USERNAME
                    path: admin/MONGO_ROOT_USERNAME
                    mode: 0444
                  - key: MONGO_ROOT_PASSWORD
                    path: admin/MONGO_ROOT_PASSWORD
                    mode: 0444
                  - key: MONGO_USERNAME
                    path: MONGO_USERNAME
                    mode: 0444
                  - key: MONGO_PASSWORD
                    path: MONGO_PASSWORD
                    mode: 0444
                  - key: MONGO_USERS_LIST
                    path: MONGO_USERS_LIST
                    mode: 0444
            - name: mongodb-scripts
              configMap:
                name: mongodb-configmap
                items:
                  - key: ensure-users.js
                    path: ensure-users.js
            - name: mongodb-configmap
              configMap:
                name: mongodb-configmap
                items:
                  - key: mongo.conf
                    path: mongo.conf
            - name: mongodb-data
              persistentVolumeClaim:
                claimName: mongodb-pvc

  # --- STORAGE CLASS ---

  - kind: StorageClass
    apiVersion: storage.k8s.io/v1
    metadata:
      name: mongodb-storageclass
      namespace: kube-starter
    provisioner: kubernetes.io/no-provisioner
    volumeBindingMode: WaitForFirstConsumer
    allowVolumeExpansion: true

  # --- PERSISTENT VOLUME ---

  - apiVersion: v1
    kind: PersistentVolume
    metadata:
      name: mongodb-pv
      namespace: kube-starter
    spec:
      capacity:
        storage: 2Gi
      volumeMode: Filesystem
      accessModes:
        - ReadWriteOnce
      persistentVolumeReclaimPolicy: Retain
      storageClassName: mongodb-storageclass
      local:
        path: /mnt/data
      nodeAffinity:
        required:
          nodeSelectorTerms:
            - matchExpressions:
                - key: kubernetes.io/hostname
                  operator: In
                  values:
                    - aws-ec2-instance

  # --- PERSISTENT VOLUME CLAIM ---

  - kind: PersistentVolumeClaim
    apiVersion: v1
    metadata:
      name: mongodb-pvc
      namespace: kube-starter
    spec:
      storageClassName: mongodb-storageclass
      accessModes:
        - ReadWriteOnce
      volumeMode: Filesystem
      volumeName: mongodb-pv
      resources:
        requests:
          storage: 2Gi
      selector:
        matchLabels:
          kubernetes.io/hostname: aws-ec2-instance

  # --- CONFIG MAP ---

  - apiVersion: v1
    kind: ConfigMap
    metadata:
      name: mongodb-configmap
      namespace: thor
    data:
      mongo.conf: |
        storage:
          dbPath: /data/db
      ensure-users.js: |
        const targetDbStr = 'test';
        const rootUser = cat('/etc/k8-test/admin/MONGO_ROOT_USERNAME');
        const rootPass = cat('/etc/k8-test/admin/MONGO_ROOT_PASSWORD');
        const usersStr = cat('/etc/k8-test/MONGO_USERS_LIST');
        const adminDb = db.getSiblingDB('admin');
        adminDb.auth(rootUser, rootPass);
        print('Successfully authenticated admin user');
        const targetDb = db.getSiblingDB(targetDbStr);
        const customRoles = adminDb
          .getRoles({rolesInfo: 1, showBuiltinRoles: false})
          .map(role => role.role)
          .filter(Boolean);
        usersStr
          .trim()
          .split(';')
          .map(s => s.split(':'))
          .forEach(user => {
            const username = user[0];
            const rolesStr = user[1];
            const password = user[2];
            if (!rolesStr || !password) {
              return;
            }
            const roles = rolesStr.split(',');
            const userDoc = {
              user: username,
              pwd: password,
            };
            userDoc.roles = roles.map(role => {
              if (!~customRoles.indexOf(role)) {
                return role;
              }
              return {role: role, db: 'admin'};
            });
            try {
              targetDb.createUser(userDoc);
            } catch (err) {
              if (!~err.message.toLowerCase().indexOf('duplicate')) {
                throw err;
              }
            }
          });

  #  --- SECRET ---

  - apiVersion: v1
    kind: Secret
    metadata:
      name: mongodb-secret
      namespace: kube-starter
    type: Opaque
    data:
      MONGO_ROOT_USERNAME: BASE_64_SECRET
      MONGO_ROOT_PASSWORD: BASE_64_SECRET
      MONGO_USERNAME: BASE_64_SECRET
      MONGO_PASSWORD: BASE_64_SECRET
      MONGO_USERS_LIST: BASE_64_SECRET

  # --- SERVICE ---

  - apiVersion: v1
    kind: Service
    metadata:
      namespace: kube-starter
      name: kube-starter-mongodb
      labels:
        app: kube-starter-mongodb-svc
    spec:
      type: NodePort
      selector:
        app: kube-starter-mongodb

      ports:
        - port: 27017
          targetPort: 27017
          nodePort: 31706

kind: List
metadata:
  resourceVersion: ""
