apiVersion: v1
items:
  # --- DEPLOYMENT ---

  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      labels:
        app: fastpyfolio-mongodb
      name: fastpyfolio-mongodb
      namespace: fastpyfolio
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: fastpyfolio-mongodb
      template:
        metadata:
          labels:
            app: fastpyfolio-mongodb
            selector: fastpyfolio-mongodb
        spec:
          containers:
            - name: fastpyfolio-mongodb
              image: mongo:7.0
              envFrom:
                - configMapRef:
                    name: fastpyfolio-mongo-config
              volumeMounts:
                - name: mongodb-data
                  mountPath: /data/db

          nodeSelector:
            name: orion

          volumes:
            - name: mongodb-data
              persistentVolumeClaim:
                claimName: mongodb-pvc

  # --- STORAGE CLASS ---

  - kind: StorageClass
    apiVersion: storage.k8s.io/v1
    metadata:
      name: mongodb-sc
      namespace: fastpyfolio
    provisioner: kubernetes.io/no-provisioner
    volumeBindingMode: WaitForFirstConsumer
    allowVolumeExpansion: true

  # --- PERSISTENT VOLUME ---

  - apiVersion: v1
    kind: PersistentVolume
    metadata:
      name: mongodb-pv
      namespace: fastpyfolio
    spec:
      capacity:
        storage: 2Gi
      volumeMode: Filesystem
      accessModes:
        - ReadWriteOnce
      persistentVolumeReclaimPolicy: Retain
      storageClassName: mongodb-sc
      local:
        path: /data/fastpyfolio/mongodb
      nodeAffinity:
        required:
          nodeSelectorTerms:
            - matchExpressions:
                - key: kubernetes.io/hostname
                  operator: In
                  values:
                    - orion

  # --- PERSISTENT VOLUME CLAIM ---

  - kind: PersistentVolumeClaim
    apiVersion: v1
    metadata:
      name: mongodb-pvc
      namespace: fastpyfolio
    spec:
      storageClassName: mongodb-sc
      accessModes:
        - ReadWriteOnce
      volumeMode: Filesystem
      volumeName: mongodb-pv
      resources:
        requests:
          storage: 2Gi
      selector:
        matchLabels:
          kubernetes.io/hostname: orion

kind: List
metadata:
  resourceVersion: ""
