apiVersion: v1
items:
  - apiVersion: v1
    data:
      .dockerconfigjson: $SECRET_FROM_ENV
    kind: Secret
    metadata:
      name: regcred-docker
      namespace: kube-starter
    type: kubernetes.io/dockerconfigjson

  - apiVersion: v1
    kind: ConfigMap
    metadata:
      name: kube-starter-config
      namespace: kube-starter
    data:
      DB_URL: kube-starter-mongodb:27017
      DB_USER: kube-starter
      DB_PASSWORD: $SECRET_FROM_ENV

kind: List
metadata:
  resourceVersion: ""
