apiVersion: v1
items:
  - apiVersion: v1
    kind: Secret
    type: kubernetes.io/dockerconfigjson
    metadata:
      name: regcred-docker
      namespace: fastpyfolio
    data:
      .dockerconfigjson: $CHANGE

  - apiVersion: v1
    kind: ConfigMap
    metadata:
      name: fastpyfolio-api-config
      namespace: fastpyfolio
    data:
      DATA: $CHANGE

  - apiVersion: v1
    kind: ConfigMap
    type: Opaque
    metadata:
      name: fastpyfolio-www-config
      namespace: fastpyfolio
    data:
      DATA: $CHANGE

  - apiVersion: v1
    kind: ConfigMap
    type: Opaque
    metadata:
      name: fastpyfolio-mongo-config
      namespace: fastpyfolio
    data:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123

kind: List
metadata:
  resourceVersion: ""
