apiVersion: v1
items:
  # --- ADMIN BACKEND ---

  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        app: kube-starter-api
      name: kube-starter-api
      namespace: kube-starter
    spec:
      ports:
        - nodePort: 31700
          port: 8001
          protocol: TCP
          targetPort: 8001
      selector:
        app: kube-starter-api
      type: NodePort

  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        app: kube-starter-www
      name: kube-starter-www
      namespace: kube-starter
    spec:
      ports:
        - nodePort: 31700
          port: 8000
          protocol: TCP
          targetPort: 8000
      selector:
        app: kube-starter-www
      type: NodePort

kind: List
metadata:
  resourceVersion: ""
